### ISSUE TITLE
Support for Kotlin Multiplatform

### ISSUE THREAD

**Issue by Dzamir** [silvercar/unleash-client-kotlin#21]
Hello, 
I want to use this library in a Kotlin Multiplatform (KMP) project: is there any plan to support it?

Otherwise, I would like to open a Pull request that uses Ktor networking instead of Java's HttpURLConnection, which is not supported in KMP.  Will something like that be accepted?

Thanks for the great work!

**Comment by louisvdaily** [comment]
@Dzamir Great question! We are having discussions internally at the moment on if we're going to do so or not. Feel free to create a PR and we can review.

Thank you for your question and usage!

**Comment by deandalm** [comment]
A concern we would have is around creating a dependency on Ktor for the library. Our initial goal was to make it work on Android and Java but it sounds like we would need to abstract the network library and use an adapter to allow users to configure what network library they want to use. That would make it easier to add something like Ktor or Okhttp.

**Comment by Dzamir** [comment]
Hello, we started working on the task but the amount of work to make the library compatible with Kotlin Multiplatform isn't trivial:
* We need to remove all references of classes that are not compatible with KMP (all classes under `java.*` and `com.google.gson.*`)
* We need to create an adapter structure for the network with a 'default' implementation

We are considering these three options:
1) Change the code and just use it internally as we need it.
2) Create a new GitHub project "unleash-client-kotlin-multiplatform" with the porting of this library to KMP.
3) Make a Pull Request to this project with all the changes.

The third options is in my opinion the most desirable, but the problem is that the changes we need to do this library are substantial. My idea is that the project can be split in 3 modules: 
* A base module with all the common classes, interfaces and common implementations
* A module with the 'java' implementation
* A module with the 'KMP' implementation

For now we are preceding internally with the first option, and when the work will be completed we will consider the second or the third option.

Thanks again for your work!

**Comment by brycehendrix** [comment]
@Dzamir would replacing gson with moshi be a good first step? I prefer moshi, so that works, it's an easy argument to make :) Otherwise, the 3rd suggestion does seem to be the best option.

**Comment by Dzamir** [comment]
Unfortunately the changes were really massive to refactor: we spent 2 days working on it and decided to abandon the task and to not port the project to multiplatform for now. 

We are using a simpler approach for now: The library is used in the Android app and passed as a reference to the multiplatform core, that will use it through a simple interface.
